version: '3.6'
services:
  postgres:
    container_name: utfparking
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: utfparking
      POSTGRES_DB: utfparking
    network_mode: bridge
    tty: true
  api:
    container_name: api
    build:
      context: ./
    image: api_utfparking
    user: application
    links:
      - postgres
    ports:
    - 8080:8080
    network_mode: bridge
    expose:
      - 8080

