version: '3.3'
services:
  postgres:
    container_name: utfparking
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: utfparking
      POSTGRES_DB: utfparking
    network_mode: bridge
    tty: true
  api:
    container_name: api
#    image: cavalcanti16/utfparking:develop
    build:
      context: ./
    image: api_utfparking
    user: application
    links:
      - postgres
    ports:
    - 8080:8080
    network_mode: bridge
    expose:
      - 8080
    volumes:
      - ./avatar:/backend/avatar
volumes:
  avatar:
