= Api - UTFParking v0.1.1
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
== Overview

Api para o sistema UTFParking, de alunos para alunos.

Esta api está agnostica de clientes deste que uso protocolos, **HTTP **, seja ele a aplicação de reconhecimento
ou web.

== Começando
Esta documentação ira auxiliar em novas implementações de __clients sides__, dando uma base
de como manipular os recursos que a API provem.

|===
| Repositório da api| https://github.com/MarcusViniciusCavalcanti/UTFParking-backend[]
| Exemplo de __client side (**React**)__| https://github.com/MarcusViniciusCavalcanti/UTFParking-frontend[]
| Exemplo de __sistema de reconhecimento (**React**)__| https://github.com/MarcusViniciusCavalcanti/UTFParking-recgonizer[]
|===

[[overview-http-verbs]]
=== HTTP Verbs

Esta Api foi construída a seguir os padrões RESTFull, tentando aderir o mais próximo
possíveis das convenções uso dos verbos HTTP

|===
| Verb | Usage

| `GET`
| Usado para recuperar recursos

| `POST`
| Usado para criar um recurso

| `PUT`
| Usado para atualizar um recurso

| `PATCH`
| Usado para atualizar um parcialmente um recurso

| `DELETE`
| Usado para remover um recurso existente.
|===

[[overview-http-status-codes]]
=== HTTP status codes

Esta Api foi construída seguindo os padrões RESTFull, tentando aderir o mais próximo
possíveis as suas convenções em seu uso dos códigos de Status HTTP

|===
| Status code | Usage

| `200 OK`
| Para requisições aceitas e processadas

| `201 Created`
| Um novo recurso foi criado com sucesso. O URI do recurso está disponível a partir da resposta
`Localização` body.link._self.href

| `204 No Content`
| Requisição foi processada e não há respostas para tal

| `400 Bad Request`
| Requisição negada, pois está mal formatada, exemplo de retorno de erro quando
a falta de um atributo, no corpo da mensagem.

| `404 Not Found`
| Este recurso não foi encontrado.

| `409 Conflict`
| O recurso já existe com as informações dada.

| `422 Unprocessable Entity`
| Requisição negada, pois não passou na validação da requisição, um atributo nulo ou
ultrapassou o limite de caracteres, são exemplos.

| `500 Internal Server Error`
| Houve um problema de processamento interno.
|===

TIP: consulte a <<erros, sessão de erros>> para avaliar as respostas de error e obter mais informações sobre os campos

[[overview-pagination]]
=== Lista de Recursos (Paginação)

Toda requisição que retorna uma lista de recursos, exemplo <<users-get-all>>, retornar um objeto, que contém: **__Page__, __Link__, __embedded__**.
Esta estrutura e útil para navegar entre uma lista de recursos.

== Objeto Page.
O objeto __Page__ contém as informações da página de recursos, contem a seguinte estrutura:
include::{snippets}/user/get/page/response-fields-beneath-page.adoc[]

Seguinte o objeto __Link__ contém os uris da página, como por exemplo a uri da última página, contém a seguinte estrutura:
include::{snippets}/user/get/page/links.adoc[]

Por fim o objeto __Embedded, contém um lista de recursos, exemplo:
include::{snippets}/user/get/page/response-body-beneath-_embedded.adoc[]

Observe que este objeto retorna uma lista do recurso usuários, sendo representado pelo __Array__ ``userRepresentationList``

IMPORTANT: Fique atento para o tipo de lista de recurso em cada url de paginação, este é apenas um exemplo
cada lista de recurso será representando por um tipo especifico consulte cada sessão para saber qual.

== Navegação entre páginas
Cada url que retorna uma lista de recursos, pode receber parâmetros que será utilizado para refinar a lista
de recursos, por exemplo a quantidade de recursos na lista ou qual página será recuperada
include::{snippets}/user/get/page/request-parameters.adoc[]

Também pode ser utilizado as uris do objeto __Links__ que é encontrado no corpo da requisição,
consulte as informações na sessão anterior, o atributo **_links**, do objeto __Page__..

[[security]]
== Segurança

As requisições feitas para Api serão STATELESS (**Sem estado**), logo a utilização de Token para
autorizar uma determinada requisição se faz necessário, assim a Api para Autorizar e autenticar um usuário
fica a cargo do JWT.

[[security-headers]]
=== Headers

Todas requisições, exceto para requisitar um token e requisições advinda do dispositivo (este utiliza outro tipo de autorização, vide: <<security-device>>),
deverá conter um Header `Authorization` contendo um portador (`Bearer`).

Exemplo:
[source,http,options="nowrap"]
----
Authorization: Bearer <TOKEN>
----

[[security-error-messagens]]
=== Resposta de error

==== Não Autenticado
Caso a requisição não contenha o header acima, excluido as que não carece de autenticação, será retornar uma mensagem
de error com **status code** `401`.

Exemplo:
include::{snippets}/security/authenticate/Login/failure/unauthorized/http-response.adoc[]

==== Não Autorizado
Para os casos de não autorizado, a mensagem de erro retornada será com **status code** `403`.

Exemplo:
include::{snippets}/security/authenticate/Login/failure/forbidden/http-response.adoc[]

##Consute <<erros, sessão de errors>> para mais informações sobre os campos da mensagem.##

[[security-autehtntication-login]]
=== Login

|===
|POST |`/ap/v1/login`
|===

Para criar um token **/api/v1/login** passando as credenciais, username e password.

IMPORTANT: As requisições para login, serão validadas, consulte: <<erros-unprocess>> para mais informações

Exemplo:
include::{snippets}/security/authenticate/Login/success/curl-request.adoc[]

include::{snippets}/security/authenticate/Login/success/response-fields.adoc[]

TIP: A Api dispõe de um endpoint para recuperar usuário dono do token, clique <<users-get-me, aqui>> para ter informações.

[[security-authorization]]

Algumas urls ou uris tem regras distintas para acesso, a qual será informada no campo `ROLE`, de cada requisição

[[roles]]
== Perfils

A api dispõe de 3 (três) perfils que são eles:

|===
|**ADMIN** |Administrador do sistema, tem total acesso aos recursos
|**OPERATOR** |Operador do sistema, tem acesso ver os reconhecimentos, liberar ou não o acesso.
|**DRIVE** |Motorista do sistema, tem acesso ao seu canal de acesso: ver seu dados, e alterar os dados
do seu carro de acesso.
|===

[[security-device]]
== Autorizando Dispositivo

Para autorizar um Dispositivo é necessário primeiro ter perfil de administrador
enviar uma requisição para a URI de configuração passando o IP do dispositivo.

Caso uma requisição for enviado de uma dispositivo sem o ip autorizado esta será negada
retornando uma mensagem de error com **STATUS CODE 401**


[[users]]
== Usuários

Usuário e um recurso da api, que representa quem utiliza o sistema, seja ele operador, motorista, ou administrador.

Os tipos de usuário será definido no campo `type`, este campo defini o comportamento do sistema para atribuição de perfils.

**SERVICE**: Servidores, professores, colaboradores em geral.

**STUDENT**: Alunos do campus.

Ostipos definem quais possíveis perfils serão atribuido a um usuário, as restrições serão:

|===
|**SERVICE** |Podera ter perfil de ADMIN, OPERATOR, DRIVE
|**STUDENTS** |Tera apenas perfil de DRIVE
|===

Para mais informações dos perfil consulte a sessão de Perfils, <<roles>>

Para controle do acesso, cada usuário poderá ter apenas um <<users-edit-car, carro>> cadastrado no sistema, porém podera alterar o carro quando lhe for conveniente
respeitando o limite de alterações.

Campos:
include::{snippets}/user/create/success/response-fields.adoc[]

Links:
include::{snippets}/user/create/success/links.adoc[]

[[users-create]]
=== Criando Usuários
|===
|METHOD|URI|ROLE

|POST
|`/ap/v1/users`
|**ADMIN**
|===

Cria um recurso usuário.

Requisição:
include::{snippets}/user/create/success/curl-request.adoc[]

Descrição dos campos:
include::{snippets}/user/create/success/request-fields.adoc[]

Resposta:
include::{snippets}/user/create/success/http-response.adoc[]

'''
==== Respostas de error

`422`
Para error de validação de campos:
include::{snippets}/user/create/error/validation/http-response.adoc[]
##Consute sessão de errors para mais informações sobre os campos da mensagem.##

`409`
Para username já existe:
include::{snippets}/user/create/error/username/http-response.adoc[]

[[users-create-avatar]]
=== Adicionando Avatar

|===
|METHOD|URI|ROLE

|POST
|`/ap/v1/users/{id}/avatar`
|**ADMIN**, **DRIVER**, **OPERATOR**
|===

Cada usuário poderá ter um um avatar, caso o usuário não faça o upload do seu avatar ele a api retornara o avatar padrão

Requisição:
include::{snippets}/user/upload/curl-request.adoc[]

A resposta será o próprio arquivo .

[[users-get]]
=== Recuperando Usuários
|===
|METHOD|URI|ROLE

|GET
|`/ap/v1/users/{ID}`
|**ADMIN**, **OPERATOR**
|===

Para recuperar um determinado usuário, deve-se informar o id do usuário.

include::{snippets}/user/get/success/path-parameters.adoc[]

Requisição:
include::{snippets}/user/get/success/curl-request.adoc[]

Resposta:
include::{snippets}/user/get/success/http-response.adoc[]

'''
==== Respostas de error
`404`
Para usuário não existe:
include::{snippets}/user/get/error/http-response.adoc[]

[[users-get-me]]
==== Recuperando Usuários da sessão
|===
|METHOD|URI|ROLE

|GET
|`/ap/v1/users/me`
|**ADMIN**, **OPERATOR**, **DRIVER**
|===

Requisição:
include::{snippets}/user/me/success/curl-request.adoc[]

Resposta:
include::{snippets}/user/me/success/http-response.adoc[]

[[users-get-all]]
==== Todos Usuários
|===
|METHOD|URI|ROLE

|GET
|`/ap/v1/users/me`
|**ADMIN**
|===

Retorna um objeto <<overview-pagination, __Page__>> **userRepresentationList** nome da lista.
que contém uma lista de <<users>>.

Caso não for encontrados recursos na base de dados, o objeto de representação estará **VAZIO**.

[[users-edit]]
=== Atualizar usuário

IMPORTANT: As urls para atualizar **PARCIALMENTE** ou **COMPLETAMENTE** um usuário
também passaram pelo processo de validação, caso a requisição não passe neste processo
um error será retornado com status `422`, consulte <<erros-unprocess>> para mais informações sobre os campos.

|===
|METHOD|URI|ROLE

|PUT
|`/ap/v1/users/{id}`
|**ADMIN**
|===

O administrador poderá alterar completamente os dados do usuário sem limite.

include::{snippets}/user/update/success/path-parameters.adoc[]

Requisição:
include::{snippets}/user/update/success/curl-request.adoc[]

Resposta:
include::{snippets}/user/update/success/http-response.adoc[]

'''
==== Respostas de error
`404`
Para usuário não existe:
include::{snippets}/user/get/error/http-response.adoc[]

[[users-edit-car]]
=== Atualizar Carro do Usuário

|===
|METHOD|URI|ROLE

|PATCH
|`/ap/v1/users/{id}/update-car`
|**ADMIN**
|===

include::{snippets}/user/update/car/success/path-parameters.adoc[]

Requisição:
include::{snippets}/user/update/car/success/curl-request.adoc[]

Resposta:
include::{snippets}/user/update/success/http-response.adoc[]

IMPORTANT: Cada usuário poderá atualizar os dados do seu carro quando lhe for mais conveniente respeitando o limite estabelecido
para tal.
Caso isso ocorra um erro será retornado com status code `422`, como demonstrado abaixo:

include::{snippets}/user/update/car/error/http-response.adoc[]

IMPORTANT: Apenas o usuário corrente poderá acessar esta URL, caso contrário o será retornado um erro
com status code `403`

[[users-delete]]
=== Deletando Usuários
|===
|METHOD|URI|ROLE

|DELETE
|`/ap/v1/users/{ID}`
|**ADMIN**
|===

Remover um determinado recurso usuário.

Requisição:
include::{snippets}/user/delete/success/curl-request.adoc[]

Resposta:
include::{snippets}/user/delete/success/http-response.adoc[]

IMPORTANT: Não é possível remover o usuário da mesma sessão,
caso isso ocorra um error será lançado com código de status ``422``. consulte <<overview-http-status-codes>>

'''
=== Respostas de error
`404`
Para usuário não existe:
include::{snippets}/user/get/error/http-response.adoc[]

[[config]]
== Configurações do Sistema

As configurações do sistema definem alguns comportamentos da API como, por exemplo, autorização do dispositivo.

A API provêm o recurso ApplicationConfiguration para manipular o comportamento da mesma.

Campos:
include::{snippets}/configurations/load/success/response-fields.adoc[]

=== Modos do Sistema
API tem até 3 comportamentos:

**AUTOMATIC**: No modo _Automático_ API após reconhecer a placa do carro é validar o acesso, emite uma notificação para o dispositivo conectado
ativar o mecanismo de abertura.

**MANUTAL**: No modo _Manual_ API após reconhecer a placa do carro notifica o _Subscribe_ dos reconhecimentos, ver sessão <<subscribes-recognizer>> para mais informações,
que uma reconhecimento foi verificado e delega para o operador a próxima ação, emitir o sinal para o dispositivo ou não.

**NONE**: No modo _Desabilitado_ a API apenas notifica o resultado do reconhecimento para o _Subscribe_.

IMPORTANT: Por padrão o sistema tem uma configuração padrão da qual define o modeSystem como desabilitado.

[[config-load]]
== Recuperando as Configurações da aplicação
|===
|METHOD|URI|ROLE

|GET
|`/ap/v1/configuration/`
|**ADMIN**
|===

Request:
include::{snippets}/configurations/load/success/curl-request.adoc[]

Resposta:
include::{snippets}/configurations/load/success/http-response.adoc[]

[[config-save]]
== Salvando Configurações do aplicação
|===
|METHOD|URI|ROLE

|POST
|`/ap/v1/configuration/`
|**ADMIN**
|===

Request:
include::{snippets}/configurations/create/success/curl-request.adoc[]

Resposta:
include::{snippets}/configurations/create/success/http-response.adoc[]

IMPORTANT: O campo **modelSystem** é `REQUERIDO` para modificar as configurações da aplicação. Consulte a sessão <<erros-unprocess>> para mais informações.

[[recognizer]]
== Reconhecimento

Os reconhecimentos enviados para API seguirá a seguinte estrutura:

Campos:
include::{snippets}/recognizer/send-plate/success/request-fields.adoc[]

== Enviar uma reconhecimento

|===
|METHOD|URI|ROLE

|POST
|`/ap/v1/configuration/`
|**DISPOSITIVO AUTORIZADO**
|===

Enviar uma requisição.
Request:
include::{snippets}/recognizer/send-plate/success/curl-request.adoc[]

Resposta:
include::{snippets}/recognizer/send-plate/success/http-response.adoc[]

[[subscribes]]
== Observadores

API tem 3 canais para um observador se inscrever para receber notificações de algumas alterações de estado da aplicação.

IMPORTANT: Ambos os canais de notificações demandam autenticação, igualmente as outras urls, é necessário adicionar o header Authorization

Os canais foram construido utilizando a Stomp sobre Websocket, exemplos de construção de clientes:

Javascript:
[source, javascript]
----
const headerName = 'Authorization';
      const token = 'Bearer <token>'
      const headers = {};
      headers[headerName] = token;

      const socket = new SockJS(`http://localhost:8080/api/v1/ws`);
      stomp = Stomp.over(socket);
      stomp.connect({"Authorization": token}, function(frame){
          stomp.subscribe('/topic/change-config', function(messageOutput) {
              console.log("New Message: "+ messageOutput);
          });
      });
----

[[subscribes-notifications]]
=== Observador de notificações do Sistema

** EM CONSTRUÇÃO**

[[subscribes-change-config]]
=== Observador de alteração de configurações

`Endpoint: /topic/change-config`

Este canal notifica uma alteração nas configurações de modo do Sistema, as respostas possíveis são:

`AUTOMATIC, NONE, MANUAL`

Mensagem:
[source, json]
----
content-length:11
message-id:0p1b3qhd-0
subscription:sub-0
content-type:application/json
destination:/topic/change-config
content-length:11

"AUTOMATIC"
----

[[subscribes-recognizer]]
=== Observador de Reconhecimento

`Endpoint: /topic/change-config`

Este endpoint poderá receber até 3 (três) mensagens distintas:

**VALIDADO**: Reconhecimento recebido corresponde a um Motorista válido e autorizado;
[source, json]
----
content-length:270
message-id:jkurrso1-1
subscription:sub-0
content-type:application/json
destination:/topic/new-recognizer
content-length:270

{
   "identified":true,
   "authorize":true,
   "driver":{
      "userId":155,
      "userName":"Fulano de Tal",
      "type":"SERVICE",
      "userAvatar":"/user/avatar/155",
      "lastAccess":"13/7/2020",
      "lastHoursAccess":"14 : 27",
      "carModel":"Car model",
      "plate":"adf12345",
      "authorizedAccess":true
   },
   "tax":77.13066
}

----
**NÃO AUTORIZADO**: Reconhecimento recebido corresponde a um Motorista válido porém não autorizado, e;
[source, json]
----
content-length:272
message-id:fq32jjkq-3
subscription:sub-0
content-type:application/json
destination:/topic/new-recognizer
content-length:272

{
   "identified":true,
   "authorize":false,
   "driver":{
      "userId":155,
      "userName":"Fulano de Tal",
      "type":"SERVICE",
      "userAvatar":"/user/avatar/155",
      "lastAccess":"13/7/2020",
      "lastHoursAccess":"14 : 45",
      "carModel":"Car model",
      "plate":"adf12345",
      "authorizedAccess":false
   },
   "tax":77.13066
}
----

TIP: Para bloquear o acesso de um Motorista consulte <<users-edit>>, para mais detalhes

**NÃO RECONHECIDO**: Reconhecimento recebido corresponde não coresponde a um motorista cadastrado na base de dados.

[source, json]
----
content-length:35
message-id:jkurrso1-0
subscription:sub-0
content-type:application/json
destination:/topic/new-recognizer
content-length:35

{
  "identified": false,
  "tax": 77.13066
}
----

** EM CONSTRUÇÃO**

[[erros]]
== Erros

As respostas de erros da Api seguem uma estrutura padrão de campos

Campos:
include::{snippets}/security/authenticate/Login/failure/forbidden/response-fields.adoc[]

Campo **Error** poderá ser dois tipos, uma String ou um array de Erros, Para erros de validação
será um array de objetos erros, denominado **fieldErros** como mostra o exemplo:

include::{snippets}/user/create/error/validation/response-body.adoc[]

[[erros-unprocess]]
=== Validação de campos

Os objetos fieldsErrors, poderão ser os seguintes:

|===
|ERROR|DESCRIPTION

|NotBlank
|O campo não pode ser nulo ou vazio.

|NotNull
|O não pode ser nulo.

|Size
|O campo deve respeitar o tamanho definido. Verifique o tamanho do valor do campo.

|ValueOfEnum
|O campo deve respeitar os valores de enum validos

|===


