= Api - UTFParking
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
== Overview

[[overview-http-verbs]]
=== HTTP Verbs

Esta Api foi construída seguindo os padrões RESTFull, tentando aderir o mais próximo
possíveis as suas conveções em seu uso dos verbos HTTP

|===
| Verb | Usage

| `GET`
| Usado para recuperar recursos

| `POST`
| Usado para crear um recurso

| `PUT`
| Usado para atualizar, parcialmente ou completamente.

| `DELETE`
| Usado para remover um recurso existente.
|===

[[overview-http-status-codes]]
=== HTTP status codes

Esta Api foi construída seguindo os padrões RESTFull, tentando aderir o mais próximo
possíveis as suas convenções em seu uso dos códigos de Status HTTP

|===
| Status code | Usage

| `200 OK`
| Para requisições aceitas e processadas

| `201 Created`
| Um novo recurso foi criado com sucesso. O URI do recurso está disponível a partir da resposta
`Localizaçao` body.link._self.href

| `204 No Content`
| Requisição foi processada e não há respostas para tal

| `400 Bad Request`
| Requsição negada, pois está mal formatada, exemplo de retorno de erro quando
a falta de um atributo.

| `404 Not Found`
| Este recurso não foi encontrado.
|===

[[overview-headers]]
=== Headers

Cada resposta tem o(s) seguinte(s) cabeçalho(s):


[[security]]
== Segurança

As requisições feitas para Api serão STATELESS (**Sem estado**), logo a utilização de Token para
autorizar uma determinada requisição se faz necessário, assim a Api para Autorizar e autenticar um usuário
fica a cargo do JWT.

[[security-headers]]
=== Headers

Toda requisição, exceto para requisitar um token e requisições advinda do dispositivo (este utiliza outro tipo de autorização, vide: <<security-device>>),
deverá conter um Header `Authorization` contendo um portador (`Bearer`).

Exemplo:
[source,http,options="nowrap"]
----
Authorization: Bearer <TOKEN>
----

[[security-error-messagens]]
=== Resposta de error

==== Não Autenticado
Caso a requisição não contenha o header acima, excluido as que não carece de autenticação, será retornar uma mensagem
de error com **status code** `401`.

Exemplo:
include::{snippets}/authenticate/Login/failure/unauthorized/http-response.adoc[]

---
==== Não Autorizado
Para os casos de não autorizado, a mensagem de erro retornada será com **status code** `403`.

Exemplo:
include::{snippets}/authenticate/Login/failure/forbidden/http-response.adoc[]


##Consute sessão de errors para mais informações sobre os campos da mensagem.##

[[security-autehtntication-login]]
=== Login

|===
|POST |`/ap/v1/login`
|===

Para criar um token **/api/v1/login** passando as credenciais, username e password.

Exemplo:
include::{snippets}/authenticate/Login/success/http-request.adoc[]

include::{snippets}/authenticate/Login/success/response-fields.adoc[]

IMPORTANT: As requisições para login, serão validadas, consulte: <<erros-badrequest>> para mais informações

[[security-device]]
=== Autorizando Dispositivo

[[users]]
== Usuários

Usuário e um recurso da api, que representa quem utiliza do sistema, seja ele operador, motorista, ou administrador

Os tipos de usuário será definido no campo `type`, este campo defini o comportamento do sistema para atribuição de perfils.

**SERVICE**: Servidores, professores, colaboradores em geral

**STUDENT**: Alunos do campus:

Os tipos definem quais possíveis perfils serão atribuido a um usuário, as restrições serão:

|===
|**SERVICE** |Podera ter perfil de ADMIN, OPERATOR, DRIVE
|**STUDENT** |Tera apenas perfil de DRIVE
|===

Para mais informações dos perfil consulte a sessão de Perfils, <<roles>>

Para controle do acesso, cada usuário poderá ter apenas um <<cars>> cadastrado no sistema, porém cada usuário
podera alterar o carro quando lhe for conveniente.

Campos:
include::{snippets}/user/create/success/response-fields.adoc[]

Links:
include::{snippets}/user/create/success/links.adoc[]

___
[[users-delete]]
=== Criando Usuários
|===
|POST |`/ap/v1/users`
|===

Cria um recurso usuário.

Requisição:
include::{snippets}/user/create/success/http-request.adoc[]

Descrição dos campos:
include::{snippets}/user/create/success/request-fields.adoc[]

Resposta:
include::{snippets}/user/create/success/http-response.adoc[]

---
##### Respostas de error

`400`
Para error de validação de campos:
include::{snippets}/user/create/error/validation/http-response.adoc[]


`409`
Para username já existe:
include::{snippets}/user/create/error/username/http-response.adoc[]


`422`
Para caso do campo id for preenchido, indicando que a URL acessa é apenas para criação
include::{snippets}/user/create/error/idExist/http-response.adoc[]

##Consute sessão de errors para mais informações sobre os campos da mensagem.##

___
[[users-delete]]
=== Deletando Usuários
|===
|DELETE |`/ap/v1/users/{id}`
|===

Remover um determinado recurso usuário.

Requisição:
include::{snippets}/user/delete/success/http-request.adoc[]

Resposta:
include::{snippets}/user/delete/success/http-response.adoc[]

IMPORTANT: Não é possível remover o usuário da mesma sessão,
caso isso ocorra um error será lançado com código de status`422`

___
[[roles]]
== Perfils

[[cars]]
== Carro


[[erros-badrequest]]
=== Bad Request

